#!/usr/bin/env bash
# This script accepts 2 arguments:
#	1. domain
#	    * type: string
#	    * what: domain name to audit
#           * mandatory: yes
#	2. subdomain
#	    * type: string
#	    * what: specific subdomain to audit
#	    * mandatory: no
# Output The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

audit_domain_func () {
if [ -z "$2" ]; then
    local sub_domains=("www" "lb-01" "web-01" "web-02")
    local domain="$1"
fi

for sub in "${sub_domains[@]}" 
do
    record_type=$(dig "$sub"."$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
    destination=$(dig "$sub"."$domain" | awk '/ANSWER SECTION:/ {getline; print $5}')

    echo "The subdomain $sub is a $record_type record and points to $destination"
done
}

sub_domains=("www" "lb-01" "web-01" "web-02")
domain="$1"

audit_domain_func sub_domains domain
