#!/usr/bin/env bash
# Install nginx on my web-01 server
# Nginx should be listening on port 80
# Return a page with string "Hello World!" when querying with GET request `Curl`

# Installing Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# Allowing nginx on firewall
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh

# Creating Sample Page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restarting the system
sudo service nginx start
