#!/usr/bin/env bash
# Install nginx on my web-01 server
# Nginx should be listening on port 80
# Return a page with string "Hello World!" when querying with GET request `Curl`

sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
#sudo ufw enable
#sudo ufw allow ssh
sudo ufw allow 'Nginx HTTP'


# Creating Sample Page
# sudo mkdir -p /var/www/html
# sudo chown -R www-data:www-data /var/www/html
# sudo chmod -R 755 /var/www/html
echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo service nginx start
