#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains at least
# one string "Hello World!"

sudo apt-get update -y
sudo apt-get install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80;
	listen [::]:80;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		return 200 'Hello World!';
	}
}
EOF


sudo service nginx restart
