#!/usr/bin/env bash
# Install nginx on my web01 server
# Redirection must be a 301 moved permanently

sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo tee /etc/nginx/sites-available/redirect_me.conf  > /dev/null <<EOF
server {
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
}
EOF

sudo service nginx restart
