#!/usr/bin/env bash
# Install nginx on my web01 server
# Redirection must be a 301 moved permanently

sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo tee /etc/nginx/sites-available/redirect_me.conf > /dev/null <<EOF
server {
    listen 80;
        server_name _;

            location /redirect_me {
                    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                        }
        }
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

sudo rm -f /etc/nginx/sites-enabled/default

sudo nginx -t && sudo systemctl reload nginx

echo "Redirection configured successfully."
