#!/usr/bin/env bash
# Configure nginx server to have a custom 404 page that contains
# "Ceci n'est pas une page"

# Installing Nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

# Enabling Nginx on firewall
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh

#  Return a page that contains the string
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirection 301 moved permanently
command="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?vQH2-TGUlwu4;\n\t}"
sudo sed -i "54i\\$command" /etc/nginx/sites-enabled/default

# 404 not found page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html 
not_found="\n\terror_page 404 \/error_404.html;\n\tlocation \/error_404_page {\n\t  root \/var\/www\/html;\n\t  internal;\n\t}"

sudo sed -i "57i\\$not_found" /etc/nginx/sites-enabled/default

# Restart the system
sudo service nginx restart
