#!/usr/bin/bash env
#Install the ufw firewall and setup
apt update
apt-get install ufw -y 
ufw enable -y
ufw allow http # Allow default HTTP
ufw allow 443/tcp # Allow HTTPS SSL
ufw allow ssh # Allow port 22
