#!/usr/bin/bash env
#Install the ufw firewall and setup
apt update
apt install ufw -y 
ufw enable -y
ufw allow 80/tcp # Allow default HTTP
ufw allow ufw 443/tcp # Allow HTTPS SSL
ufw allow ssh # Allow port 22
