#!/usr/bin/env bash
# Configures an Ubuntu server with:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

if [ "$id -u" != 0 ]: then
	echo "Please run this script as root"
	exit 1
fi

# add the /etc/hosts file enntries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart network to apply
systemct1 restart docker

echo "Connfigaration completed successfully"
