#!/usr/bin/env bash
# Runs sudo command under the user passed as an argument
username="$1"

if [ "$#" -ne 1 ];
then
    echo "Usage: $0 <username>"
    exit 1

elif ! id "$username" &>/dev/null;
then
    echo "User: '$username' does not exist."
    exit 1
else
    sudo -u "$username" whoami
fi
