#!/usr/bin/env bash
# nginx must be listening on all active IPs on port 8080
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user\s*www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
