#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# cannot use apt-get remove

sed -i 's/user\s*www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

service nginx restart
