#!/usr/bin/env bash
# SSH client configuration must be configured to use the private key ~/.ssh/school
# SSH client configuration must be configured to refuse to authenticate using a password

Host 100.25.160.40
	IdetifyFile ~/.ssh/school
	PreferredAuthentications publickey
	PasswordAuthetication no

